### ISSUE TITLE
Feat: Workflow for Closing Old Issues

### ISSUE THREAD

**Issue by Asymtode712** [Nactore-Org/Nacto-Care#137]
### Describe the feature

This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

### Add ScreenShots

![Close Old Iss](https://github.com/Nactore-Org/Nacto-Care/assets/115717746/593f1a5e-772e-40d1-b739-7fe4e67faa9d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@Harshil-Jani please assign me this issue

**Comment by Harshil-Jani** [comment]
I am afraid of having such an automation. In past, I was working on projects where we almost picked up things from 2 years old while working on an issue. I am talking about rust-miniscript project and it's more helpful as maintainer to have issues open even if they are old because it gives an idea to prioritize as we make progress.
