### ISSUE TITLE
Login Signup using JWT

### ISSUE THREAD

**Issue by Rhythm1710** [Nactore-Org/Nacto-Care#69]
### Describe the feature

I can implement login and sign up using jwt tokens 

### Add ScreenShots

![image](https://github.com/Nactore-Org/Nacto-Care/assets/65298117/8d668b00-2338-486d-9218-ed6ed3aeb959)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shashankbhosagi** [comment]
Checkout issue number #7 [Backend] : Implement Login and Register routes using JWT 
Already the work has be assigned :)

**Comment by Rhythm1710** [comment]
Ok @shashankbhosagi Is there anything else I can do in the backend?

**Comment by shashankbhosagi** [comment]
> Ok @shashankbhosagi Is there anything else I can do in the backend?

I am also participant, I was also interested in same thing but it was already assigned so I thought instead of you waiting for 1day or more let tell you it has been already assigned so you could think on something different.

**Comment by Harshil-Jani** [comment]
@shashankbhosagi Thanks a lot for identifying the duplication but I was just reviewing the PR for that issue few mins ago :) and I feel that I can re-assign to you or @Rhythm1710 . The reason why I am saying this is because it haunts me to review an irrelevant change that is huge and pointless.

Refer #77 

Or if you can assist me to help the contributor to push correct change then too it would be really helpful :)
