### ISSUE TITLE
Feat: Featuring Best Nurses

### ISSUE THREAD

**Issue by Hemashree21** [Nactore-Org/Nacto-Care#93]
### Describe the feature

In the home page or when we click the Book Nurse button, a block of 4-5 nurses who have high ratings and are most frequently contacted can be displayed.

@Harshil-Jani what do you think?

### Add ScreenShots

![image](https://github.com/Nactore-Org/Nacto-Care/assets/138188163/d4ef5f26-8eee-4318-b6f0-381f43fc88e8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshil-Jani** [comment]
@Hemashree21 We are just focussing on homecare model for initial phase. Let Tata 1mg and Pharmeasy do the work on medicine delivery and stuff. For the video consultation the main aim is to get enough patients up on the platform and enough nurses on. 

Moreover,  It needs to put some thought because video consultations are mostly appropriate with doctors. For nurse, we aim to solve basic healthcare needs and create an income stream for nurses just like ola uber did for drivers and siwggy zomato did for delivery partners.

**Comment by Hemashree21** [comment]
@Harshil-Jani Ohh okay, I'll just try to find some other issues to work on, and if there are any issues you currently have please do let me know so that I can work on it.

**Comment by Hemashree21** [comment]
![image](https://github.com/Nactore-Org/Nacto-Care/assets/138188163/5796b3a4-6cb8-40d3-ab8b-4a377ee1b02f)

And there is this link called Brand Center in the Footer, if you can tell me what exactly it is I can work on that

**Comment by Harshil-Jani** [comment]
@Hemashree21 In future it would represent Nactore organization. So like TATA is a parent company and then it has multiple branches like TATA Steel, TATA Power, TATA moters etc. in similar ways we have Nactore as a parent and then it has Nacto-Care, Nacto-Rail, Nacto-Fin etc. 

But still, I am not sure content wise what should be in Brand Center. If you are happy to research on various sites if they have this section at all and what needs to go in, I am happy to assign and then you can raise PR accordingly.

**Comment by Hemashree21** [comment]
Sure I will research and get back

**Comment by Harshil-Jani** [comment]
@Hemashree21 Awesome. Please raise a new issue when you are ready to start.
